### ISSUE TITLE
Incompatibility with Robosuite Textures

### ISSUE THREAD

**Issue by peterdavidfagan** [ARISE-Initiative/robosuite-task-zoo#3]
@zhuyifengzju the following textures present in the multitask_kitchen.py don't seem to be supported in the most recent version of Robosuite (see https://github.com/ARISE-Initiative/robosuite/tree/master/robosuite/models/assets/textures for supported textures):

(1) Orange
(2) Apple 
(3) Mellon
(4) Cake

I am happy to submit a pull request to the Robosuite repository given the official .png files you have used for the textures. 

Code snippet with unsupported texture:
https://github.com/ARISE-Initiative/robosuite-task-zoo/blob/499d7ff6140e3cde92c5aa16c94702e10ec613be/robosuite_task_zoo/environments/manipulation/multitask_kitchen.py#L240

**Code Sample Generating Error:**
import numpy as np

import robosuite as suite
from robosuite import load_controller_config
from robosuite.wrappers import DataCollectionWrapper, VisualizationWrapper

from robosuite_task_zoo.environments.manipulation import *

controller_config = load_controller_config(default_controller = "OSC_POSE")

config = {
    "robots": ["Panda"],
    "controller_configs": controller_config
}

env = multitask_kitchen.MultitaskKitchenDomain(
        **config,
        has_renderer=True,
        has_offscreen_renderer=False,
        render_camera="agentview",
        ignore_done=True,
        use_camera_obs=False,
        reward_shaping=True,
        control_freq=20,
    )

**Error:**
AssertionError: Error: Requested invalid texture. Got Orange. Valid options are:
dict_keys(['WoodRed', 'WoodGreen', 'WoodBlue', 'WoodLight', 'WoodDark', 'WoodTiles', 'WoodPanels', 'WoodgrainGray', 'PlasterCream', 'PlasterPink', 'PlasterYellow', 'PlasterGray', 'PlasterWhite', 'BricksWhite', 'Metal', 'SteelBrushed', 'SteelScratched', 'Brass', 'Bread', 'Can', 'Ceramic', 'Cereal', 'Clay', 'Dirt', 'Glass', 'FeltGray', 'Lemon'])

**Comment by zhuyifengzju** [comment]
Hi! 

    thanks for reasining this quesiton. I think it's because of some legacy implementations. These textures are not supposed to be used in the BUDS paper. I'll remove the part that requires these textures.
