### ISSUE TITLE
Will robosuite-task-zoo and its accompanying datasets(BUDS) work with the latest version of robosuite-V1.4 ?

### ISSUE THREAD

**Issue by BrightMoonStar** [ARISE-Initiative/robosuite-task-zoo#5]
Great work!
Could you please let me know which version of robosuite does robosuite-task-zoo correspond to? Will robosuite-task-zoo and its accompanying datasets(BUDS) work with the latest version of robosuite-V1.4?
Thank you very much!

**Comment by zhuyifengzju** [comment]
Hi,
Thanks for your interest in this effort. Unfortunately, I don't think the data will play well with robosuite-V1.4, as we've made some critical changes to the simulation logic. I recommend you to install the robosuite 1.3 version. If you have any more specific questions, let me know.

**Comment by BrightMoonStar** [comment]
Thank you for your reply！ This is very important to me！
